package dev.quinntyx.charon.backup

import kotlinx.coroutines.test.runTest
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

class CharonBackupArchiveTest {
    private val archive = CharonBackupArchive()

    @Test
    fun `round trip preserves logical records and original receipt bytes`() = runTest {
        val original = BackupSnapshot(
            createdAtEpochMillis = 1_735_689_600_123,
            records = listOf(
                BackupRecord("transactions", "tx-2", "{\"minorUnits\":1299,\"currency\":\"EUR\"}"),
                BackupRecord("folders", "cash", "{\"name\":\"Café wallet\"}"),
            ),
            receipts = listOf(
                BackupReceipt("receipt/with a source ID", "image/jpeg", byteArrayOf(0, 1, 2, -1)),
                BackupReceipt("scan-2", "image/png", "not actually a png in this unit test".toByteArray()),
            ),
        )
        val bytes = write(original)
        val validated = archive.validate(ByteArrayInputStream(bytes))
        val restoredReceipts = linkedMapOf<String, ByteArray>()
        archive.streamReceipts(ByteArrayInputStream(bytes), validated) { receipt, content ->
            restoredReceipts[receipt.stableId] = content.readBytes()
        }

        assertEquals(original.createdAtEpochMillis, validated.data.createdAtEpochMillis)
        assertEquals(
            original.records.associate { it.collection to JSONObject(it.payloadJson).toString() },
            validated.data.records.associate { it.collection to it.payloadJson },
        )
        assertEquals(original.receipts.map { it.stableId }.toSet(), restoredReceipts.keys)
        original.receipts.forEach { expected ->
            assertArrayEquals(
                expected.openStream().use { it.readBytes() },
                restoredReceipts.getValue(expected.stableId),
            )
        }
    }

    @Test
    fun `export opens and copies a large receipt as a stream`() {
        val receiptSize = 16L * 1024L * 1024L
        var opens = 0
        var source: GeneratedInputStream? = null
        val snapshot = sampleSnapshot().copy(
            receipts = listOf(
                BackupReceipt("large", "image/jpeg", receiptSize) {
                    opens += 1
                    GeneratedInputStream(receiptSize).also { source = it }
                },
            ),
        )

        val output = ByteArrayOutputStream()
        archive.write(snapshot, output)

        assertEquals(1, opens)
        assertEquals(receiptSize, source!!.bytesRead)
        assertTrue(source!!.largestRequest <= DEFAULT_BUFFER_SIZE)
        // Repeated generated bytes compress strongly; this assertion also avoids a test-side 16 MiB copy.
        assertTrue(output.size() < 256 * 1024)
    }

    @Test
    fun `validation and restore stream a receipt larger than metadata memory limit`() = runTest {
        val streamingArchive = CharonBackupArchive(
            CharonBackupArchive.Limits(
                maxEntryBytes = 20L * 1024L * 1024L,
                maxTotalBytes = 24L * 1024L * 1024L,
                maxMetadataEntryBytes = 1_024,
                maxEntries = 10,
                maxRecords = 10,
                maxReceipts = 10,
            ),
        )
        val receiptSize = 16L * 1024L * 1024L
        val snapshot = BackupSnapshot(
            createdAtEpochMillis = 1,
            records = emptyList(),
            receipts = listOf(
                BackupReceipt("large", "image/jpeg", receiptSize) { GeneratedInputStream(receiptSize) },
            ),
        )
        val bytes = ByteArrayOutputStream().also { streamingArchive.write(snapshot, it) }.toByteArray()
        val validated = streamingArchive.validate(ByteArrayInputStream(bytes))
        var restoredBytes = 0L

        streamingArchive.streamReceipts(ByteArrayInputStream(bytes), validated) { _, content ->
            val buffer = ByteArray(2_113)
            while (true) {
                val count = content.read(buffer)
                if (count < 0) break
                restoredBytes += count
            }
        }

        assertEquals(receiptSize, validated.receipts.single().metadata.size)
        assertEquals(receiptSize, restoredBytes)
    }

    @Test
    fun `changed receipt content is rejected by checksum validation`() {
        val bytes = write(sampleSnapshot())
        val changed = rewriteZip(bytes) { name, content ->
            if (name.startsWith("receipts/")) content + 99 else content
        }

        val error = assertThrows(InvalidBackupException::class.java) {
            archive.validate(ByteArrayInputStream(changed))
        }

        assertTrue(error.message.orEmpty().contains("mismatch"))
    }

    @Test
    fun `unsupported version is reported distinctly`() {
        val changed = rewriteZip(write(sampleSnapshot())) { name, content ->
            if (name == "manifest.json") {
                JSONObject(content.toString(Charsets.UTF_8))
                    .put("version", 999)
                    .toString()
                    .toByteArray()
            } else {
                content
            }
        }

        assertThrows(UnsupportedBackupVersionException::class.java) {
            archive.validate(ByteArrayInputStream(changed))
        }
    }

    @Test
    fun `path traversal entry is rejected before extraction or restore`() {
        val malicious = zipOf(
            "manifest.json" to "{}".toByteArray(),
            "receipts/../../outside.jpg" to byteArrayOf(1, 2, 3),
        )

        val error = assertThrows(InvalidBackupException::class.java) {
            archive.validate(ByteArrayInputStream(malicious))
        }

        assertTrue(error.message.orEmpty().contains("Unsafe ZIP entry path"))
    }

    @Test
    fun `duplicate stable IDs are rejected during export`() {
        val duplicate = sampleSnapshot().copy(
            records = listOf(
                BackupRecord("transactions", "same", "{\"value\":1}"),
                BackupRecord("transactions", "same", "{\"value\":2}"),
            ),
        )

        assertThrows(InvalidBackupException::class.java) { write(duplicate) }
    }

    @Test
    fun `entry size limit applies to decompressed content`() {
        val limited = CharonBackupArchive(
            CharonBackupArchive.Limits(
                maxEntryBytes = 32,
                maxTotalBytes = 1_024,
                maxMetadataEntryBytes = 32,
                maxEntries = 10,
                maxRecords = 10,
                maxReceipts = 10,
            ),
        )
        val compressedLargeEntry = zipOf("manifest.json" to ByteArray(100) { 0 })

        val error = assertThrows(InvalidBackupException::class.java) {
            limited.validate(ByteArrayInputStream(compressedLargeEntry))
        }

        assertTrue(error.message.orEmpty().contains("size limit"))
    }

    @Test
    fun `receipt source size mismatch is rejected during streaming export`() {
        val snapshot = sampleSnapshot().copy(
            receipts = listOf(
                BackupReceipt("short", "image/jpeg", 10) { ByteArrayInputStream(byteArrayOf(1, 2)) },
            ),
        )

        val error = assertThrows(InvalidBackupException::class.java) { write(snapshot) }

        assertTrue(error.message.orEmpty().contains("Size mismatch"))
    }

    private fun sampleSnapshot() = BackupSnapshot(
        createdAtEpochMillis = 1234,
        records = listOf(BackupRecord("transactions", "tx-1", "{\"minorUnits\":2500}")),
        receipts = listOf(BackupReceipt("receipt-1", "image/jpeg", byteArrayOf(5, 4, 3, 2, 1))),
    )

    private fun write(snapshot: BackupSnapshot): ByteArray =
        ByteArrayOutputStream().also { archive.write(snapshot, it) }.toByteArray()

    private fun rewriteZip(
        source: ByteArray,
        transform: (String, ByteArray) -> ByteArray,
    ): ByteArray {
        val entries = mutableListOf<Pair<String, ByteArray>>()
        ZipInputStream(ByteArrayInputStream(source)).use { input ->
            while (true) {
                val entry = input.nextEntry ?: break
                entries += entry.name to transform(entry.name, input.readBytes())
            }
        }
        return zipOf(*entries.toTypedArray())
    }

    private fun zipOf(vararg entries: Pair<String, ByteArray>): ByteArray {
        val output = ByteArrayOutputStream()
        ZipOutputStream(output).use { zip ->
            entries.forEach { (name, content) ->
                zip.putNextEntry(ZipEntry(name))
                zip.write(content)
                zip.closeEntry()
            }
        }
        return output.toByteArray()
    }

    private class GeneratedInputStream(private val totalSize: Long) : InputStream() {
        var bytesRead = 0L
            private set
        var largestRequest = 0
            private set

        override fun read(): Int = if (bytesRead >= totalSize) {
            -1
        } else {
            bytesRead += 1
            (bytesRead and 0xff).toInt()
        }

        override fun read(bytes: ByteArray, offset: Int, length: Int): Int {
            if (bytesRead >= totalSize) return -1
            largestRequest = maxOf(largestRequest, length)
            val count = minOf(length.toLong(), totalSize - bytesRead).toInt()
            for (index in 0 until count) {
                bytes[offset + index] = ((bytesRead + index) and 0xff).toByte()
            }
            bytesRead += count
            return count
        }
    }
}
